[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
  for = "*.woff2
  [headers.values]
    Cache-Control: public,max-age=31536000,immutable
