[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
[[redirects]]
  from = "/blog/how-to-defer-offscreen-images-the-modern-and-fast-way/"
  to = "/blog/how-to-defer-offscreen-images/"
  status = 301
[[edge_functions]]
  pattern = "/_astro/(.+)_(.+).(?:jpg|jpeg|png|webp|avif)"
  function = "image-rewrite"
