[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[headers]]
  for = "/_astro-optimized/*.avif"
  [headers.values]
    Cache-Control = "private,max-age=31536000,immutable"
[[headers]]
  for = "/_astro/*.avif"
  [headers.values]
    Cache-Control = "private,max-age=31536000,immutable"
[[redirects]]
  from = "/blog/how-to-defer-offscreen-images-the-modern-and-fast-way/"
  to = "/blog/how-to-defer-offscreen-images/"
  status = 301
[[edge_functions]]
  pattern = "\/_astro\/.+\.(?:jpg|jpeg|png|webp|avif)"
  function = "image-rewrite"
