/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Notifications {
  createdAt: Generated<string>;
  id: Generated<number>;
  slug: string;
}

export interface Posts {
  id: Generated<number>;
  slug: string;
  viewCount: number;
}

export interface DB {
  notifications: Notifications;
  posts: Posts;
}
