# name: Playwright Tests
# on:
#   push:
#     branches: [main, master]
#   pull_request:
#     branches: [main, master]
# jobs:
#   playwright:
#     name: "Playwright Tests"
#     runs-on: ubuntu-latest
#     container:
#       image: mcr.microsoft.com/playwright:v1.25.2-focal
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v2
#         with:
#           node-version: "14"
#       - name: Install dependencies
#         run: npm ci
#       - name: Build
#         run: npm run build
#       - name: Run your tests
#         # run: npx playwright test
#         run: HOME=/root npx playwright test --update-snapshots
#       - name: Upload results
#         uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: playwright-report
#           path: |
#             tests
#             playwright-report/
#           retention-days: 30

# steps:
#   - uses: actions/checkout@v3
#   - uses: actions/setup-node@v2
#     with:
#       node-version: '14'
#   - name: Install dependencies
#     run: npm ci
#   - name: Build
#     run: npm run build
#   - name: Install Playwright
#     run: npx playwright install --with-deps
#   - name: Run your tests
#     run: npm test
#   - name: Upload test results
#     if: always()
#     uses: actions/upload-artifact@v2
#     with:
#       name: playwright-report
#       path: playwright-report

name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i -g npm@8
      - run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npm run build
      - run: npx playwright install --with-deps ${{ matrix.browser }} chromium
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:ui -- --project=${{ matrix.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.browser }}-${{ matrix.os }}-test-results
          path: test-results
          path: |
            test-results
            tests
