name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Run docker
        run: docker run --rm --network host -w /work/ mcr.microsoft.com/playwright:v1.25.0-focal /bin/bash -c "npm ci"
      - name: Build
        run: docker run --rm --network host -w /work/ mcr.microsoft.com/playwright:v1.25.0-focal /bin/bash -c "npm run build"
      - name: Run Playwright tests
        run: docker run --rm --network host -w /work/ mcr.microsoft.com/playwright:v1.25.0-focal /bin/bash -c "npx playwright test"
      - name: Upload results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
