name: Push or PR workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        # with:
        #   node-version: 16.x
        #   cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
